source 'https://rubygems.org'
ruby '2.5.3'
gem 'addressable'
gem 'ginseng-core', git: 'https://github.com/pooza/ginseng-core.git'
gem 'httparty'
gem 'pg'
gem 'rake'
gem 'rubocop'
gem 'sanitize'
gem 'thin'
