source 'https://rubygems.org'
ruby '2.7.0'
gem 'bootsnap'
gem 'ginseng-core', github: 'pooza/ginseng-core'
gem 'ginseng-postgres', github: 'pooza/ginseng-postgres'
gem 'ginseng-web', github: 'pooza/ginseng-web'
gem 'sanitize'
