source 'https://rubygems.org'
ruby '2.5.5'
gem 'ginseng-core', git: 'https://github.com/pooza/ginseng-core.git'
gem 'ginseng-postgres', git: 'https://github.com/pooza/ginseng-postgres.git'
gem 'rubocop'
gem 'sanitize'
