package:
  version: 2.0.7
  url: https://github.com/pooza/radish-feed
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
entries:
  max: 100
feed:
  minutes: 5
tag:
  cacheable: []
postgres:
  dsn: postgres://postgres@localhost:5432/mastodon
puma:
  port: 3001
  pidfile: tmp/pids/puma.pid
  rackup: app/initializer/config.ru
