package:
  version: 1.3.1
  url: https://github.com/pooza/radish-feed
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
twitter:
  length:
    tweet: 140
    uri: 24
entries:
  max: 200
  default: 100
db:
  host: localhost
  user: postgres
  password: null
  dbname: mastodon
  port: 5432
