package:
  version: 1.3.13
  url: https://github.com/pooza/radish-feed
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
test:
  server:
    accounts:
      limit: 5
twitter:
  length:
    tweet: 140
    uri: 24
entries:
  max: 100
  default: 20
postgres:
  dsn: postgres://postgres@localhost:5432/mastodon
