package:
  version: 2.0.5
  url: https://github.com/pooza/radish-feed
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
entries:
  max: 100
feed:
  minutes: 5
tag:
  cacheable: []
postgres:
  dsn: postgres://postgres@localhost:5432/mastodon
thin:
  timeout: 30
  port: 3001
  environment: production
  rackup: app/initializer/config.ru
