site: >-
  SELECT
  var,
  value
  FROM settings
  WHERE (var IN ('site_title','site_description','site_contact_username'))
  AND (thing_type IS NULL);
registered: >-
  SELECT
  id
  FROM accounts
  WHERE (domain IS NULL)
  AND (locked='f')
  AND (username=$1);
account_timeline: >-
  SELECT
  toots.uri,
  toots.created_at,
  toots.text
  FROM statuses AS toots
  INNER JOIN accounts ON toots.account_id=accounts.id
  WHERE (accounts.domain IS NULL)
  AND (accounts.locked='f')
  AND (accounts.username=$1)
  AND (toots.visibility=0)
  AND (toots.text<>'')
  AND (toots.uri IS NOT NULL)
  AND (toots.text !~ '@[_a-z0-9]+(@[-.a-z0-9]+)?[ \n]')
  ORDER BY toots.created_at DESC
  LIMIT $2 OFFSET 0;
local_timeline: >-
  SELECT
  toots.uri,
  toots.created_at,
  '[@' || accounts.username || '] ' || toots.text AS text
  FROM statuses AS toots
  INNER JOIN accounts ON toots.account_id=accounts.id
  WHERE (accounts.domain IS NULL)
  AND (accounts.locked='f')
  AND (toots.visibility=0)
  AND (toots.text<>'')
  AND (toots.uri IS NOT NULL)
  ORDER BY toots.created_at DESC
  LIMIT $1 OFFSET 0;
