site: >-
  SELECT
  var,
  value
  FROM settings
  WHERE (var IN ('site_title','site_description','site_contact_username'))
  AND (thing_type IS NULL);
registered: >-
  SELECT
  id
  FROM accounts
  WHERE (domain IS NULL)
  AND (locked='f')
  AND (username='<%= params[:account] %>');
account_timeline: >-
  SELECT
  toots.uri,
  toots.created_at,
  toots.text,
  toots.spoiler_text
  FROM statuses AS toots
  INNER JOIN accounts ON toots.account_id=accounts.id
  LEFT JOIN media_attachments AS attachments ON toots.id=attachments.status_id
  WHERE (accounts.domain IS NULL)
  AND (accounts.locked='f')
  AND (accounts.username='<%= params[:account] %>')
  AND (toots.visibility=0)
  AND (toots.uri IS NOT NULL)
  AND (toots.text !~ '@[_a-zA-Z0-9]+(@[-.a-z0-9]+)?[ \n]')
  <% if params[:actor_type] == 'Service' %>
  AND (accounts.actor_type='Service')
  <% elsif params[:actor_type] == 'Person' %>
  AND ((accounts.actor_type='Person') OR (accounts.actor_type IS NULL))
  <% end %>
  <% if params[:hashtag] %>
  AND (toots.text ~ '#<%= params[:hashtag] %>')
  <% end %>
  GROUP BY
  toots.uri,
  toots.created_at,
  toots.text,
  toots.spoiler_text
  ORDER BY toots.created_at DESC
  LIMIT <%= params[:entries] %> OFFSET 0;
local_timeline: >-
  SELECT
  toots.uri,
  toots.created_at,
  '[@' || accounts.username || '] ' || toots.text AS text,
  toots.spoiler_text
  FROM statuses AS toots
  INNER JOIN accounts ON toots.account_id=accounts.id
  LEFT JOIN media_attachments AS attachments ON toots.id=attachments.status_id
  WHERE (accounts.domain IS NULL)
  AND (accounts.locked='f')
  AND (toots.visibility=0)
  AND (toots.uri IS NOT NULL)
  <% if params[:actor_type] == 'Service' %>
  AND (accounts.actor_type='Service')
  <% elsif params[:actor_type] == 'Person' %>
  AND ((accounts.actor_type='Person') OR (accounts.actor_type IS NULL))
  <% end %>
  <% if params[:hashtag] %>
  AND (toots.text ~ '#<%= params[:hashtag] %>')
  <% end %>
  GROUP BY
  toots.uri,
  toots.created_at,
  accounts.username,
  toots.text,
  toots.spoiler_text
  ORDER BY toots.created_at DESC
  LIMIT <%= params[:entries] %> OFFSET 0;
