version: 1

update_configs:
  - package_manager: ruby:bundler
    directory: /
    update_schedule: daily
    target_branch: master
    allowed_updates:
      - match:
          update_type: all
    version_requirement_updates: 'off'
